version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: simplepass
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  keycloak: # for further improvement on security
    profiles:
      - "not-start"
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: simplepass
    ports:
      - "8080:8080"
    command: ["start-dev", "--db=postgres"]