logging.level.org.springframework.security: DEBUG

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: simplepass
